/*
 * $Id: stdlib.c,v 2.9 2001/02/19 17:07:18 dulimart Exp $
 *
 * Author: Hans Dulimarta  [dulimart@computer.org]
 * Description:
 *    This files contains partial replacements of some Unix system calls 
 * for PowerPC machine, specifically for the CME-555 evaluation board.
 *
 * $Log: stdlib.c,v $
 * Revision 2.9  2001/02/19 17:07:18  dulimart
 * Moved sleep and usleep to sleep.cc
 *
 * Revision 2.8  2000/12/06 17:47:38  dulimart
 * Move sleep() and usleep() to sleep.cc because usleep needs to be compiled with g++
 *
 * Revision 2.7  2000/11/16 19:56:32  dulimart
 * Modified usleep() to blocking call
 *
 * Revision 2.6  2000/10/02 20:19:44  dulimart
 * Deleted code for accessing TimeBase, and simplified exit()
 *
 * Revision 2.5  2000/08/02 15:43:55  dulimart
 * Disabled internal flash before exiting.
 *
 * Revision 2.4  2000/07/14 22:49:46  dulimart
 * Implemented gettimeofday()
 *
 * Revision 2.3  2000/07/10 16:41:07  dulimart
 * Added qsm_reset in _exit()
 *
 * Revision 2.2  2000/06/29 13:44:39  dulimart
 * Removed debugging messages.
 *
 * Revision 2.1  2000/05/23 16:14:44  dulimart
 * Added elapsetime().
 *
 * Revision 2.0  2000/04/25 12:56:31  dulimart
 * Initial revision for PPC-555
 *
 *
 * Copyright (c) 2000  Hans Dulimarta, Ph.D.
 */

#include <sys/time.h>
#include "io.h"
#include "stdlib.h"
#include "usiu.h"
#ifdef ram
#include "qsm.h"
#endif

time_t time (time_t *p) {
   if (p)
      return (*p = USIU.rtc >> 6);
   else
      return USIU.rtc >> 6;
}

int gettimeofday (struct timeval *tv, struct timezone *_) {
   if (tv) {
      tv->tv_sec  = USIU.rtc >> 6;
      tv->tv_usec = (USIU.rtc % 64) * 15625; /* converted to microsecond */
      return 0;
   }
   else
      return -1;
}

void _exit (int _) {
   puts ("\nPress the reset button to start the code\n");
#if 1
   asm ("li     %r3,0x800"); /* enable internal flash */
   asm ("mtspr  638,%r3");
   asm ("1:     b 1b");
#else
#ifdef ram
   /* Disable internal flash */
	asm ("mfimmr %r3");
	asm ("li %r4,0x800");
	asm ("andc %r3,%r3,%r4");
	asm ("mtspr 638,%r3");
   qsm_reset();
	USIU.dmbr = 0x00000001; /* Enable dual mapping and map to CS0 */
	USIU.dmor = 0x60000000;
#endif

	asm ("li %r3,0x100"); /* system reset at address 0x100 */
	asm ("mtlr %r3");
	/* asm ("blr"); Not needed, blr is automatically generated by compiler */ 
#endif
}

double elapsetime (time_t *t) {
   static time_t *ref;

   if (t) {
      ref = t;
      return 0.0;
   }
   else 
      return difftime (time(0), *ref);
}
